# fly.toml app configuration file generated for stancy-bot on 2024-09-10T19:53:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stancy-bot'
primary_region = 'iad'

[build]

[[mounts]]
  source = 'stancy_data'
  destination = '/data'

[[services]]
  protocol = ''
  internal_port = 0
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  ports = []
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  BOT_CONFIG = "/data/config.json"